version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm start
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    restart: always
